package ru.binbank.fnsservice.contracts;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.23 at 10:02:59 PM MSK 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения о руководителе (заместителе руководителя) налогового органа
 *
 * <p>Java class for RukNoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RukNoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FIO" type="{}FioType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="KlasChin">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="250"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0420\u0443\u043a\u041d\u041e\u0422\u0438\u043f", propOrder = {
        "\u0444\u0438\u043e"
})
public class RukNoType {

    @XmlElement(name = "\u0424\u0418\u041e", required = true)
    protected FioType fio;
    @XmlAttribute(name = "\u041a\u043b\u0430\u0441\u0427\u0438\u043d")
    protected String klasChin;

    /**
     * Gets the value of the fio property.
     *
     * @return
     *     possible object is
     *     {@link FioType }
     *
     */
    public FioType getFIO() {
        return fio;
    }

    /**
     * Sets the value of the fio property.
     *
     * @param value
     *     allowed object is
     *     {@link FioType }
     *
     */
    public void setFIO(FioType value) {
        this.fio = value;
    }

    /**
     * Gets the value of the klasChin property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKlasChin() {
        return klasChin;
    }

    /**
     * Sets the value of the klasChin property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKlasChin(String value) {
        this.klasChin = value;
    }

}
