package ru.binbank.fnsservice.contracts;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.23 at 10:02:59 PM MSK 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения о налоговом органе 
 *
 * <p>Java class for SvNoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SvNoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="KodNo" use="required" type="{}ИФНСТип" />
 *       &lt;attribute name="NaimNo" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="160"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0421\u0432\u041d\u041e\u0422\u0438\u043f")
public class SvNoType {

    @XmlAttribute(name = "\u041a\u043e\u0434\u041d\u041e", required = true)
    protected String kodNo;
    @XmlAttribute(name = "\u041d\u0430\u0438\u043c\u041d\u041e", required = true)
    protected String naimNo;

    /**
     * Gets the value of the kodNo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKodNo() {
        return kodNo;
    }

    /**
     * Sets the value of the kodNo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKodNo(String value) {
        this.kodNo = value;
    }

    /**
     * Gets the value of the naimNo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNaimNo() {
        return naimNo;
    }

    /**
     * Sets the value of the naimNo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNaimNo(String value) {
        this.naimNo = value;
    }

}
