package ru.binbank.fnsservice.contracts;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.23 at 10:02:59 PM MSK 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения об учреждении Банка России
 *
 * <p>Java class for UbrType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UbrType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BIK" use="required" type="{}BIKТип" />
 *       &lt;attribute name="NaimUbr" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="160"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="INNBR" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;length value="10"/>
 *             &lt;enumeration value="7702235133"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="KPPUBR" use="required" type="{}КППТип" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0423\u0411\u0420\u0422\u0438\u043f")
public class UbrType {

    @XmlAttribute(name = "\u0411\u0418\u041a", required = true)
    protected String bik;
    @XmlAttribute(name = "\u041d\u0430\u0438\u043c\u0423\u0411\u0420", required = true)
    protected String naimUbr;
    @XmlAttribute(name = "\u0418\u041d\u041d\u0411\u0420", required = true)
    protected String innbr;
    @XmlAttribute(name = "\u041a\u041f\u041f\u0423\u0411\u0420", required = true)
    protected String kppubr;

    /**
     * Gets the value of the bik property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBIK() {
        return bik;
    }

    /**
     * Sets the value of the bik property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBIK(String value) {
        this.bik = value;
    }

    /**
     * Gets the value of the naimUbr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNaimUbr() {
        return naimUbr;
    }

    /**
     * Sets the value of the naimUbr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNaimUbr(String value) {
        this.naimUbr = value;
    }

    /**
     * Gets the value of the innbr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getINNBR() {
        return innbr;
    }

    /**
     * Sets the value of the innbr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setINNBR(String value) {
        this.innbr = value;
    }

    /**
     * Gets the value of the kppubr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKPPUBR() {
        return kppubr;
    }

    /**
     * Sets the value of the kppubr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKPPUBR(String value) {
        this.kppubr = value;
    }

}
