package ru.binbank.fnsservice.contracts;

import java.util.Date;

/**
 * Запрос выписки.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.05.23 at 10:02:59 PM MSK
//

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ZapnoVipis">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="svNo" type="{}svNoType"/>
 *                   &lt;choice>
 *                     &lt;element name="svBank" type="{}bankType"/>
 *                     &lt;element name="svUBR" type="{}ubrType"/>
 *                   &lt;/choice>
 *                   &lt;element name="SvPl">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;choice>
 *                               &lt;element name="PlUl" type="{}PlUlType"/>
 *                               &lt;element name="PlIp" type="{}PlIpType"/>
 *                               &lt;element name="PFL" type="{}PflType"/>
 *                             &lt;/choice>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="zaPeriod">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="DateBeg" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="DateEnd" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;choice>
 *                     &lt;element name="poVsem">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;length value="1"/>
 *                           &lt;enumeration value="1"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="poUkazannim" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="NomSch" use="required">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="20"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/attribute>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                   &lt;element name="rukovoditel" type="{}rukNoType"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="nomZapr" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;minLength value="1"/>
 *                       &lt;maxLength value="20"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="dateZapr" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="kodOsnov" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;length value="4"/>
 *                       &lt;pattern value="[0-1]{4}"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="vidZapr" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;length value="1"/>
 *                       &lt;pattern value="[1-8]{1}"/>
 *                       &lt;enumeration value="3"/>
 *                       &lt;enumeration value="5"/>
 *                       &lt;enumeration value="8"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="osnovZapr" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;minLength value="1"/>
 *                       &lt;maxLength value="1000"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="typeZapr" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;length value="1"/>
 *                       &lt;enumeration value="1"/>
 *                       &lt;enumeration value="2"/>
 *                       &lt;enumeration value="3"/>
 *                       &lt;enumeration value="4"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="idES" use="required" type="{}GUIDТип" />
 *       &lt;attribute name="typeInf" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;length value="10"/>
 *             &lt;enumeration value="ZapnoVipis"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="versProg" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="40"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="telOtpr" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="20"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="dolznOtpr" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="100"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="famOtpr" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="60"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="versForm" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;totalDigits value="4"/>
 *             &lt;fractionDigits value="2"/>
 *             &lt;enumeration value="3.00"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "\u0437\u0430\u043f\u043d\u043e\u0432\u044b\u043f\u0438\u0441"
})
@XmlRootElement(name = "\u0424\u0430\u0439\u043b")
public class ZSVRequest {

    @XmlElement(name = "\u0417\u0410\u041f\u041d\u041e\u0412\u042b\u041f\u0418\u0421", required = true)
    protected ZSVRequest.ZapnoVipis ZapnoVipis;
    @XmlAttribute(name = "\u0418\u0434\u042d\u0421", required = true)
    protected String idES;
    @XmlAttribute(name = "\u0422\u0438\u043f\u0418\u043d\u0444", required = true)
    protected String typeInf;
    @XmlAttribute(name = "\u0412\u0435\u0440\u0441\u041f\u0440\u043e\u0433", required = true)
    protected String versProg;
    @XmlAttribute(name = "\u0422\u0435\u043b\u041e\u0442\u043f\u0440", required = true)
    protected String telOtpr;
    @XmlAttribute(name = "\u0414\u043e\u043b\u0436\u043d\u041e\u0442\u043f\u0440", required = true)
    protected String dolznOtpr;
    @XmlAttribute(name = "\u0424\u0430\u043c\u041e\u0442\u043f\u0440", required = true)
    protected String famOtpr;
    @XmlAttribute(name = "\u0412\u0435\u0440\u0441\u0424\u043e\u0440\u043c", required = true)
    protected BigDecimal versForm;

    /**
     * Gets the value of the ZapnoVipis property.
     *
     * @return
     *     possible object is
     *     {@link ZSVRequest.ZapnoVipis }
     *
     */
    public ZSVRequest.ZapnoVipis getZapnoVipis() {
        return ZapnoVipis;
    }

    /**
     * Sets the value of the ZapnoVipis property.
     *
     * @param value
     *     allowed object is
     *     {@link ZSVRequest.ZapnoVipis }
     *
     */
    public void setZapnoVipis(ZSVRequest.ZapnoVipis value) {
        this.ZapnoVipis = value;
    }

    /**
     * Gets the value of the idES property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getidES() {
        return idES;
    }

    /**
     * Sets the value of the idES property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setidES(String value) {
        this.idES = value;
    }

    /**
     * Gets the value of the typeInf property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String gettypeInf() {
        return typeInf;
    }

    /**
     * Sets the value of the typeInf property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void settypeInf(String value) {
        this.typeInf = value;
    }

    /**
     * Gets the value of the versProg property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getversProg() {
        return versProg;
    }

    /**
     * Sets the value of the versProg property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setversProg(String value) {
        this.versProg = value;
    }

    /**
     * Gets the value of the telOtpr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String gettelOtpr() {
        return telOtpr;
    }

    /**
     * Sets the value of the telOtpr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void settelOtpr(String value) {
        this.telOtpr = value;
    }

    /**
     * Gets the value of the dolznOtpr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getdolznOtpr() {
        return dolznOtpr;
    }

    /**
     * Sets the value of the dolznOtpr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setdolznOtpr(String value) {
        this.dolznOtpr = value;
    }

    /**
     * Gets the value of the famOtpr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getfamOtpr() {
        return famOtpr;
    }

    /**
     * Sets the value of the famOtpr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setfamOtpr(String value) {
        this.famOtpr = value;
    }

    /**
     * Gets the value of the versForm property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getversForm() {
        return versForm;
    }

    /**
     * Sets the value of the versForm property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setversForm(BigDecimal value) {
        this.versForm = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="svNo" type="{}svNoType"/>
     *         &lt;choice>
     *           &lt;element name="svBank" type="{}bankType"/>
     *           &lt;element name="svUBR" type="{}ubrType"/>
     *         &lt;/choice>
     *         &lt;element name="SvPl">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="PlUl" type="{}PlUlType"/>
     *                     &lt;element name="PlIp" type="{}PlIpType"/>
     *                     &lt;element name="PFL" type="{}PflType"/>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="zaPeriod">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="DateBeg" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="DateEnd" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;choice>
     *           &lt;element name="poVsem">
     *             &lt;simpleType>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                 &lt;length value="1"/>
     *                 &lt;enumeration value="1"/>
     *               &lt;/restriction>
     *             &lt;/simpleType>
     *           &lt;/element>
     *           &lt;element name="poUkazannim" maxOccurs="unbounded">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;attribute name="NomSch" use="required">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="20"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/attribute>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/choice>
     *         &lt;element name="rukovoditel" type="{}rukNoType"/>
     *       &lt;/sequence>
     *       &lt;attribute name="nomZapr" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="20"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="dateZapr" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="kodOsnov" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;length value="4"/>
     *             &lt;pattern value="[0-1]{4}"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="vidZapr" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;length value="1"/>
     *             &lt;pattern value="[1-8]{1}"/>
     *             &lt;enumeration value="3"/>
     *             &lt;enumeration value="5"/>
     *             &lt;enumeration value="8"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="osnovZapr" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="1000"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="typeZapr" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;length value="1"/>
     *             &lt;enumeration value="1"/>
     *             &lt;enumeration value="2"/>
     *             &lt;enumeration value="3"/>
     *             &lt;enumeration value="4"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "\u0441\u0432\u041d\u041e",
            "\u0441\u0432\u0411\u0430\u043d\u043a",
            "\u0441\u0432\u0423\u0411\u0420",
            "\u0441\u0432\u041f\u043b",
            "\u0437\u0430\u041f\u0435\u0440\u0438\u043e\u0434",
            "\u043f\u043e\u0412\u0441\u0435\u043c",
            "\u043f\u043e\u0423\u043a\u0430\u0437\u0430\u043d\u043d\u044b\u043c",
            "\u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c"
    })
    public static class ZapnoVipis {

        @XmlElement(name = "\u0421\u0432\u041d\u041e", required = true)
        protected SvNoType svNo;
        @XmlElement(name = "\u0421\u0432\u0411\u0430\u043d\u043a")
        protected BankType svBank;
        @XmlElement(name = "\u0421\u0432\u0423\u0411\u0420")
        protected UbrType svUBR;
        @XmlElement(name = "\u0421\u0432\u041f\u043b", required = true)
        protected ZSVRequest.ZapnoVipis.SvPl svPl;
        @XmlElement(name = "\u0417\u0430\u041f\u0435\u0440\u0438\u043e\u0434", required = true)
        protected ZSVRequest.ZapnoVipis.ZaPeriod zaPeriod;
        @XmlElement(name = "\u041f\u043e\u0412\u0441\u0435\u043c")
        protected String poVsem;
        @XmlElement(name = "\u041f\u043e\u0423\u043a\u0430\u0437\u0430\u043d\u043d\u044b\u043c")
        protected List<ZSVRequest.ZapnoVipis.poUkazannim> poUkazannim;
        @XmlElement(name = "\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c", required = true)
        protected RukNoType rukovoditel;
        @XmlAttribute(name = "\u041d\u043e\u043c\u0417\u0430\u043f\u0440", required = true)
        protected String nomZapr;
        @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u0417\u0430\u043f\u0440", required = true)
        protected XMLGregorianCalendar dateZapr;
        @XmlAttribute(name = "\u041a\u043e\u0434\u041e\u0441\u043d\u043e\u0432", required = true)
        protected String kodOsnov;
        @XmlAttribute(name = "\u0412\u0438\u0434\u0417\u0430\u043f\u0440", required = true)
        protected String vidZapr;
        @XmlAttribute(name = "\u041e\u0441\u043d\u043e\u0432\u0417\u0430\u043f\u0440", required = true)
        protected String osnovZapr;
        @XmlAttribute(name = "\u0422\u0438\u043f\u0417\u0430\u043f\u0440", required = true)
        protected String typeZapr;

        /**
         * Gets the value of the svNo property.
         *
         * @return
         *     possible object is
         *     {@link svNoType }
         *
         */
        public SvNoType getsvNo() {
            return svNo;
        }

        /**
         * Sets the value of the svNo property.
         *
         * @param value
         *     allowed object is
         *     {@link svNoType }
         *
         */
        public void setsvNo(SvNoType value) {
            this.svNo = value;
        }

        /**
         * Gets the value of the svBank property.
         *
         * @return
         *     possible object is
         *     {@link bankType }
         *
         */
        public BankType getsvBank() {
            return svBank;
        }

        /**
         * Sets the value of the svBank property.
         *
         * @param value
         *     allowed object is
         *     {@link bankType }
         *
         */
        public void setsvBank(BankType value) {
            this.svBank = value;
        }

        /**
         * Gets the value of the svUBR property.
         *
         * @return
         *     possible object is
         *     {@link ubrType }
         *
         */
        public UbrType getsvUBR() {
            return svUBR;
        }

        /**
         * Sets the value of the svUBR property.
         *
         * @param value
         *     allowed object is
         *     {@link ubrType }
         *
         */
        public void setsvUBR(UbrType value) {
            this.svUBR = value;
        }

        /**
         * Gets the value of the svPl property.
         *
         * @return
         *     possible object is
         *     {@link ZSVRequest.ZapnoVipis.SvPl }
         *
         */
        public ZSVRequest.ZapnoVipis.SvPl getSvPl() {
            return svPl;
        }

        /**
         * Sets the value of the svPl property.
         *
         * @param value
         *     allowed object is
         *     {@link ZSVRequest.ZapnoVipis.SvPl }
         *
         */
        public void setSvPl(ZSVRequest.ZapnoVipis.SvPl value) {
            this.svPl = value;
        }

        /**
         * Gets the value of the zaPeriod property.
         *
         * @return
         *     possible object is
         *     {@link ZSVRequest.ZapnoVipis.zaPeriod }
         *
         */
        public ZSVRequest.ZapnoVipis.ZaPeriod getzaPeriod() {
            return zaPeriod;
        }

        /**
         * Sets the value of the zaPeriod property.
         *
         * @param value
         *     allowed object is
         *     {@link ZSVRequest.ZapnoVipis.zaPeriod }
         *
         */
        public void setzaPeriod(ZSVRequest.ZapnoVipis.ZaPeriod value) {
            this.zaPeriod = value;
        }

        /**
         * Gets the value of the poVsem property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getpoVsem() {
            return poVsem;
        }

        /**
         * Sets the value of the poVsem property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setpoVsem(String value) {
            this.poVsem = value;
        }

        /**
         * Gets the value of the poUkazannim property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the poUkazannim property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getpoUkazannim().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ZSVRequest.ZapnoVipis.poUkazannim }
         *
         *
         */
        public List<ZSVRequest.ZapnoVipis.poUkazannim> getpoUkazannim() {
            if (poUkazannim == null) {
                poUkazannim = new ArrayList<ZSVRequest.ZapnoVipis.poUkazannim>();
            }
            return this.poUkazannim;
        }

        /**
         * Gets the value of the rukovoditel property.
         *
         * @return
         *     possible object is
         *     {@link rukNoType }
         *
         */
        public RukNoType getrukovoditel() {
            return rukovoditel;
        }

        /**
         * Sets the value of the rukovoditel property.
         *
         * @param value
         *     allowed object is
         *     {@link rukNoType }
         *
         */
        public void setrukovoditel(RukNoType value) {
            this.rukovoditel = value;
        }

        /**
         * Gets the value of the nomZapr property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getnomZapr() {
            return nomZapr;
        }

        /**
         * Sets the value of the nomZapr property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setnomZapr(String value) {
            this.nomZapr = value;
        }

        /**
         * Gets the value of the dateZapr property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getdateZapr() {
            return dateZapr;
        }

        /**
         * Sets the value of the dateZapr property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setdateZapr(XMLGregorianCalendar value) {
            this.dateZapr = value;
        }

        /**
         * Gets the value of the kodOsnov property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getkodOsnov() {
            return kodOsnov;
        }

        /**
         * Sets the value of the kodOsnov property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setkodOsnov(String value) {
            this.kodOsnov = value;
        }

        /**
         * Gets the value of the vidZapr property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getvidZapr() {
            return vidZapr;
        }

        /**
         * Sets the value of the vidZapr property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setvidZapr(String value) {
            this.vidZapr = value;
        }

        /**
         * Gets the value of the osnovZapr property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getosnovZapr() {
            return osnovZapr;
        }

        /**
         * Sets the value of the osnovZapr property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setosnovZapr(String value) {
            this.osnovZapr = value;
        }

        /**
         * Gets the value of the typeZapr property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String gettypeZapr() {
            return typeZapr;
        }

        /**
         * Sets the value of the typeZapr property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void settypeZapr(String value) {
            this.typeZapr = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="DateBeg" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="DateEnd" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ZaPeriod {

            @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u041d\u0430\u0447", required = true)
            protected XMLGregorianCalendar dateBeg;
            @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u041a\u043e\u043d", required = true)
            protected XMLGregorianCalendar dateEnd;

            /**
             * Gets the value of the dateBeg property.
             *
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getDateBeg() {
                return dateBeg;
            }

            /**
             * Sets the value of the dateBeg property.
             *
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public void setDateBeg(XMLGregorianCalendar value) {
                this.dateBeg = value;
            }

            /**
             * Gets the value of the dateEnd property.
             *
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getDateEnd() {
                return dateEnd;
            }

            /**
             * Sets the value of the dateEnd property.
             *
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public void setDateEnd(XMLGregorianCalendar value) {
                this.dateEnd = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="NomSch" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="1"/>
         *             &lt;maxLength value="20"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class poUkazannim {

            @XmlAttribute(name = "\u041d\u043e\u043c\u0421\u0447", required = true)
            protected String nomSch;

            /**
             * Gets the value of the nomSch property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNomSch() {
                return nomSch;
            }

            /**
             * Sets the value of the nomSch property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNomSch(String value) {
                this.nomSch = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="PlUl" type="{}PlUlType"/>
         *           &lt;element name="PlIp" type="{}PlIpType"/>
         *           &lt;element name="PFL" type="{}PflType"/>
         *         &lt;/choice>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "\u043f\u043b\u042e\u041b",
                "\u043f\u043b\u0418\u041f",
                "\u043f\u0444\u043b"
        })
        public static class SvPl {

            @XmlElement(name = "\u041f\u043b\u042e\u041b")
            protected PlUlType plUl;
            @XmlElement(name = "\u041f\u043b\u0418\u041f")
            protected PlIpType plIp;
            @XmlElement(name = "\u041f\u0424\u041b")
            protected PflType pfl;

            /**
             * Gets the value of the plUl property.
             *
             * @return
             *     possible object is
             *     {@link PlUlType }
             *
             */
            public PlUlType getPlUl() {
                return plUl;
            }

            /**
             * Sets the value of the plUl property.
             *
             * @param value
             *     allowed object is
             *     {@link PlUlType }
             *
             */
            public void setPlUl(PlUlType value) {
                this.plUl = value;
            }

            /**
             * Gets the value of the plIp property.
             *
             * @return
             *     possible object is
             *     {@link PlIpType }
             *
             */
            public PlIpType getPlIp() {
                return plIp;
            }

            /**
             * Sets the value of the plIp property.
             *
             * @param value
             *     allowed object is
             *     {@link PlIpType }
             *
             */
            public void setPlIp(PlIpType value) {
                this.plIp = value;
            }

            /**
             * Gets the value of the pfl property.
             *
             * @return
             *     possible object is
             *     {@link PflType }
             *
             */
            public PflType getPFL() {
                return pfl;
            }

            /**
             * Sets the value of the pfl property.
             *
             * @param value
             *     allowed object is
             *     {@link PflType }
             *
             */
            public void setPFL(PflType value) {
                this.pfl = value;
            }

        }

    }

}
